# Generated by Django 4.1.1 on 2024-09-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('medico', 'Médico'), ('paciente', 'Paciente')], max_length=10),
        ),
    ]
