# Generated by Django 5.1.1 on 2024-10-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
