# Generated by Django 5.1.1 on 2024-11-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chatmessage_image_alter_chatmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
    ]
