# Generated by Django 4.2 on 2024-12-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='picture_image',
            new_name='user_picture',
        ),
    ]
