# Generated by Django 4.2 on 2024-12-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='horario_atencion',
        ),
        migrations.AddField(
            model_name='doctor',
            name='days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
