# Generated by Django 4.2 on 2024-12-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_doctor_horario_atencion_doctor_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
