# Generated by Django 4.2 on 2024-12-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_consulta_motivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='motivo',
            new_name='alergias',
        ),
        migrations.AddField(
            model_name='consulta',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
