# Generated by Django 4.2 on 2024-12-18 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_rename_motivo_consulta_alergias_consulta_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('id_card', models.CharField(max_length=25)),
                ('genero', models.CharField(max_length=10)),
                ('tipo_sangre', models.CharField(max_length=3)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='core.consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='core.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
