# Generated by Django 5.1.1 on 2024-12-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_consulta_genero_alter_consulta_tipo_sangre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
