# Generated by Django 4.2 on 2024-12-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='doc_receta',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/recetas/'),
        ),
    ]
