# Generated by Django 5.1.1 on 2024-12-18 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='core.consulta'),
        ),
    ]
