# Generated by Django 4.2 on 2025-02-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_consulta_tipo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/pdf_adjunt_consultas/'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='embarazo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='virtual', max_length=10),
        ),
    ]
