# Generated by Django 5.1.1 on 2024-12-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_receta_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='doc_receta',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/recetas/'),
        ),
    ]
