# Generated by Django 4.2 on 2025-02-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_consulta_archivo_pdf_consulta_embarazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/chat_pdfs/'),
        ),
    ]
