# Generated by Django 5.1.1 on 2025-01-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_receta_doc_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=10),
        ),
    ]
