# Generated by Django 4.2 on 2025-03-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_consulta_token_reprogramacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consulta_duracion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
