# Generated by Django 5.1.1 on 2025-02-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_consulta_embarazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/chat_files/'),
        ),
    ]
