# Generated by Django 4.2 on 2025-04-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_doctor_consulta_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='cirugia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='enfermedad_base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='modalidad_consulta',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Hibrida')], max_length=15, null=True),
        ),
    ]
