# Generated by Django 5.1.1 on 2025-02-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_chatmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/chat_pdfs/'),
        ),
    ]
