# Generated by Django 5.1.1 on 2025-02-19 04:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_chatmessage_file_chatmessage_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='token_reprogramacion',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
