# Generated by Django 4.2 on 2025-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_consulta_cirugia_consulta_enfermedad_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=255),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id_card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='id_card',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo_sangre',
            field=models.CharField(max_length=255),
        ),
    ]
