# Generated by Django 4.2 on 2025-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_consulta_estado_alter_consulta_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='modalidad_consulta',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida')], max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty'], name='idx_doctor_specialty'),
        ),
    ]
