# Generated by Django 5.1.1 on 2025-02-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_consulta_token_reprogramacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='token_reprogramacion',
        ),
    ]
