# Generated by Django 5.1.1 on 2025-02-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_consulta_token_reprogramacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='token_reprogramacion',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
