# Generated by Django 5.1.1 on 2025-02-20 00:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_consulta_token_reprogramacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='token_reprogramacion',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
