# Generated by Django 5.1.1 on 2025-03-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_consulta_token_reprogramacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consulta_duracion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
