# Generated by Django 5.1.1 on 2025-03-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_doctor_consulta_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='modalidad_consulta',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
