# Generated by Django 5.1.1 on 2025-03-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_doctor_modalidad_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='modalidad_consulta',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Hibrida')], max_length=15, null=True),
        ),
    ]
