# Generated by Django 5.1.1 on 2025-03-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_doctor_modalidad_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='cirugias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='enfermedad_base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medicacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
