# Generated by Django 5.1.1 on 2025-03-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_consulta_cirugias_consulta_enfermedad_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='cirugias',
            new_name='cirugia',
        ),
    ]
