# Generated by Django 5.1.1 on 2025-04-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_consulta_estado_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
