# Generated by Django 5.1.1 on 2025-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_receta_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='genero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='genero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
