# Generated by Django 5.1.1 on 2025-04-13 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_consulta_estado_alter_consulta_genero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty'], name='idx_doctor_specialty'),
        ),
    ]
