# Generated by Django 5.1.1 on 2025-04-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_doctor_idx_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='modalidad_consulta',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('híbrida', 'Híbrida')], max_length=15, null=True),
        ),
    ]
